# Generated by Django 4.2.7 on 2023-11-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghibli_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMerchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salt', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
